// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.187
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileDiffer
{
    static class Vsix
    {
        public const string Id = "20fa04de-c067-4534-9ce9-9025165d90c1";
        public const string Name = "File Differ";
        public const string Description = @"The easiest way to diff two files directly from Solution Explorer ";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Christopher Butler";
        public const string Tags = "compare, diff, files";
    }
}
