// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.187
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileDiffer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDiffFilesCommandPackageString = "3a77a702-c564-4d96-ae1a-9a03f5ba4e27";
        public const string guidDiffFilesCommandPackageCmdSetString = "bf6aa7a2-cdb3-4fbf-afad-0a67eb8d68d0";
        public const string guidImagesString = "50878d6c-92d5-403e-9dee-9405894437be";
        public static Guid guidDiffFilesCommandPackage = new Guid(guidDiffFilesCommandPackageString);
        public static Guid guidDiffFilesCommandPackageCmdSet = new Guid(guidDiffFilesCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int DiffFilesCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
